### ISSUE TITLE
Can't build tex file with version 0.3.0

### ISSUE THREAD

**Issue by johnblommers** [hamaluik/mkbook#1]
The manual tells us how to build a `tex` file but it fails because `mkbook` does not know about the `-l` flag::

```bash
mkbook build -l ./print/book.tex
error: Found argument '-l' which wasn't expected, or isn't valid in this context

USAGE:
    mkbook build [OPTIONS]

For more information try --help
```

I installed `mkbook` with cargo. This nets version 0.3.0.

**Update**

This is fixed in version 0.4.0 which I installed from source code as follows:

```bash
cd ~/Downloads
git clone https://github.com/hamaluik/mkbook.git
cd mkbook
cargo run -- build -i docs-src -o docs
cargo install --path . --force
```

**Comment by hamaluik** [comment]
Yea, sorry about that.. I plan on pushing 0.4 to crates.io soon, just need to smooth a couple more wrinkles out first!
